# -*- coding: utf-8 -*-
"""ProjetoCalculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFADk7XsExcKbYzbTM4RKrvItK6QOCN_

# Calculadora Python

## Vamos começar? A seguir insira dois números e logo após vamos decidir qual operação fazer.
"""

from re import sub
num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))

soma = num1 + num2
subtracao = num1 - num2
multiplicacao = num1 * num2
divisao = num1 / num2
pnum1 = num1 / 100
pnum2 = num2 / 100
porcentagem1 = num1 / pnum2
porcentagem2 = num2 / pnum1


print("-------------------------")
print("Muito bem, agora temos o valor " , num1)
print("E também o valor" , num2)
print("-------------------------")
print("Agora selecione a operação que deseja fazer")
print("1 - Adição(+)")
print("2 - Subtração(-)")
print("3 - Multiplicação(*)")
print("4 - Divisão(/)")
print("5 - Porcentagem do valor 1 sobre o valor 2(%)")
print("6 - Porcentagem do valor 2 sobre o valor 1(%)")
print("0 - Encerrar aplicação(X)")
print("-------------------------")

opcao = int(input("Digite o número da opção desejada: "))
print("-------------------------")

if opcao == 0:
  print("Aplicação encerrada!")
if opcao == 1:
  print("A opção escolhida foi a: (",opcao,") Adição(+)")
  print("Resultado: ",num1," + ",num2," = ",soma)
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")
if opcao == 2:
  print("A opção escolhida foi a: (",opcao,") Subtração(-)")
  print("Resultado: ",num1," - ",num2," = ",subtracao)
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")
if opcao == 3:
  print("A opção escolhida foi a: (",opcao,") Multiplicação(*)")
  print("Resultado: ",num1," * ",num2," = ",multiplicacao)
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")
if opcao == 4:
  print("A opção escolhida foi a: (",opcao,") Divisão(/)")
  print("Resultado: ",num1," / ",num2," = ",divisao)
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")
if opcao == 5:
  print("A opção escolhida foi a: (",opcao,") Porcentagem do valor 1 sobre o valor 2(%)")
  print("Resultado: O valor ",num1," representa ",porcentagem1,"% de ",num2)
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")
if opcao == 6:
  print("A opção escolhida foi a: (",opcao,") Porcentagem do valor 2 sobre o valor 1(%)")
  print("Resultado: O valor ",num2," representa ",porcentagem2,"% de ",num1)
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")
if opcao > 6:
  print("Opção inválida!")
  opcao = int(input("Digite o número da opção desejada: "))
  print("-------------------------")

