# -*- coding: utf-8 -*-
"""ProjetoCalculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFADk7XsExcKbYzbTM4RKrvItK6QOCN_

# Calculadora Python

## Vamos começar? A seguir insira dois números e logo após vamos decidir qual operação fazer.
"""

from re import sub

print("-------------------------------------------------")
print("------------------ Olá, mundo! ------------------")
print("-------------------------------------------------")
print("Bem-vindo(a) a minha primeira calculadora Python")
print("Ela é bem simples, mas espero que goste :D")
print("Você irá informar dois números e logo em seguida")
print("escolher algumas opções aritméticas disponíveis")
print("-------------------------------------------------")

##Bloco para identificar se os campos input's são números válidos
while True:
    try:
        num1 = int(input("Digite o primeiro número: "))
        break
    except ValueError:
        print("Erro! Digite apenas números.")
while True:
    try:
        num2 = int(input("Digite o segundo número: "))
        break
    except ValueError:
        print("Erro! Digite apenas números.")

##Declaração de variáveis
pnum1 = num1 / 100
pnum2 = num2 / 100
porcentagem1 = num1 / pnum2
porcentagem2 = num2 / pnum1

##Bloco de mensagens de inicialização da calculadora
print("-------------------------")
print("Muito bem, agora temos o valor " , num1)
print("E também o valor" , num2)
print("-------------------------")
print("Agora selecione a operação que deseja fazer")
print("1 - Adição(+)")
print("2 - Subtração(-)")
print("3 - Multiplicação(*)")
print("4 - Divisão(/)")
print("5 - Porcentagem do valor 1 sobre o valor 2(%)")
print("6 - Porcentagem do valor 2 sobre o valor 1(%)")
print("0 - Encerrar aplicação(X)")
print("-------------------------")

while True:
    ##Bloco para identificar se a opção escolhida é um número inteiro
    entrada = input("Escolha a opção desejada: ")
    if not entrada.isdigit():
        print("-------------------------")
        print("ERRO: Por favor, informe APENAS números entre 0 e 6.")
        print("-------------------------")
        continue
    opcao = int(entrada)
    if opcao < 0 or opcao > 6:
        print("-------------------------")
        print("Opção inválida! Informe APENAS números entre 0 a 6.")
        print("-------------------------")
        continue
    ##Bloco de ação da calculadora
    if opcao == 1:
      print("A opção escolhida foi a: (",opcao,") Adição(+)")
      print("Resultado: ",num1," + ",num2," = ",num1 + num2)
      print("-------------------------")
      
    elif opcao == 2:
      print("A opção escolhida foi a: (",opcao,") Subtração(-)")
      print("Resultado: ",num1," - ",num2," = ",num1 - num2)
      print("-------------------------")
      
    elif opcao == 3:
      print("A opção escolhida foi a: (",opcao,") Multiplicação(*)")
      print("Resultado: ",num1," * ",num2," = ",num1 * num2)
      print("-------------------------")
  
    elif opcao == 4:
      print("A opção escolhida foi a: (",opcao,") Divisão(/)")
      if num2 != 0:
        print("Resultado: ",num1," / ",num2," = ",num1 / num2)
      else:
            print("Erro: Divisão por zero não é permitida.")
      print("-------------------------")
  
    elif opcao == 5:
      print("A opção escolhida foi a: (",opcao,") Porcentagem do valor 1 sobre o valor 2(%)")
      print("Resultado: O valor ",num1," representa ",porcentagem1,"% de ",num2)
      print("-------------------------")
  
    elif opcao == 6:
      print("A opção escolhida foi a: (",opcao,") Porcentagem do valor 2 sobre o valor 1(%)")
      print("Resultado: O valor ",num2," representa ",porcentagem2,"% de ",num1)
      print("-------------------------")
  
    elif opcao == 0:
      print("Aplicação encerrada!")
      exit()

    elif opcao > 6 or opcao < 0:
      print("Opção inválida!")
      print("-------------------------")

  
  


